POST http://localhost:3003/graphic/insert
Content-Type: application/json

{
    "first_name":"Adeire",
    "last_name":"Moreira",
    "participation": 20
}

###
GET  http://localhost:3003/graphic/select
Content-Type: application/json
###
PUT http://localhost:3003/graphic/update/a568b08c-00bd-472f-aec7-b80e52c5d644
Content-Type: application/json

{
    "first_name":"Eduardo",
    "last_name":"Osiro",
    "participation": 20
}
###
DELETE http://localhost:3003/graphic/delete/a568b08c-00bd-472f-aec7-b80e52c5d644
Content-Type: application/json


